import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

// Import compiled translation JSONs (build-time)
import en from '../../lang/en.json'
import tr from '../../lang/tr.json'

/**
 * i18n Configuration
 * 
 * Translations are imported at build time (not runtime fetch)
 * Generated by: php artisan translations:export
 */

// Get locale from Laravel (set in HTML tag) - only for client-side
const locale = typeof document !== 'undefined' 
  ? (document.documentElement.lang || 'en')
  : 'en'

i18n
  .use(initReactI18next)
  .init({
    resources: {
      en: { translation: en },
      tr: { translation: tr },
    },
    lng: locale,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false, // React already escapes
    },
  })

/**
 * Initialize i18n for SSR
 * Called from ssr.jsx with server-side locale and translations
 */
export function initI18n(locale: string, translations: Record<string, any>) {
  if (!i18n.isInitialized) {
    i18n
      .use(initReactI18next)
      .init({
        resources: {
          [locale]: { translation: translations },
        },
        lng: locale,
        fallbackLng: 'en',
        interpolation: {
          escapeValue: false,
        },
      })
  } else {
    // If already initialized, just change language and add resources
    i18n.addResourceBundle(locale, 'translation', translations, true, true)
    i18n.changeLanguage(locale)
  }
}

export { i18n }
