// Mock data for rankings and king elections

export const mockPlayers = [
  {
    userId: 1,
    userName: "DragonSlayer",
    userSlug: "dragon-slayer",
    level: 83,
    rebirthLevel: 2,
    className: "Warrior",
    classIcon: "warrior",
    nationText: "Karus",
    expPercentage: 75,
    formattedLoyalty: "125,450",
    symbol: "dragon",
    clanId: 1,
    clanName: "BlackLegion",
    clanSlug: "black-legion",
    clanIcon: null,
    titleName: "KING",
    rank: 1,
  },
  {
    userId: 2,
    userName: "ShadowMage",
    userSlug: "shadow-mage",
    level: 82,
    rebirthLevel: 1,
    className: "Mage",
    classIcon: "mage",
    nationText: "Human",
    expPercentage: 90,
    formattedLoyalty: "118,200",
    symbol: "phoenix",
    clanId: 2,
    clanName: "Phoenix",
    clanSlug: "phoenix",
    clanIcon: null,
    titleName: "DUKE",
    rank: 2,
  },
  {
    userId: 3,
    userName: "HolyPriest",
    userSlug: "holy-priest",
    level: 81,
    rebirthLevel: 0,
    className: "Priest",
    classIcon: "priest",
    nationText: "Human",
    expPercentage: 45,
    formattedLoyalty: "98,750",
    symbol: "none",
    clanId: 2,
    clanName: "Phoenix",
    clanSlug: "phoenix",
    clanIcon: null,
    titleName: null,
    rank: 3,
  },
  {
    userId: 4,
    userName: "NightBlade",
    userSlug: "night-blade",
    level: 80,
    rebirthLevel: 1,
    className: "Rogue",
    classIcon: "rogue",
    nationText: "Karus",
    expPercentage: 60,
    formattedLoyalty: "87,300",
    symbol: "skull",
    clanId: 1,
    clanName: "BlackLegion",
    clanSlug: "black-legion",
    clanIcon: null,
    titleName: null,
    rank: 4,
  },
  {
    userId: 5,
    userName: "IceQueen",
    userSlug: "ice-queen",
    level: 79,
    rebirthLevel: 0,
    className: "Mage",
    classIcon: "mage",
    nationText: "Human",
    expPercentage: 30,
    formattedLoyalty: "76,500",
    symbol: "ice",
    clanId: 3,
    clanName: "Frozen",
    clanSlug: "frozen",
    clanIcon: null,
    titleName: "DUCHESS",
    rank: 5,
  },
  {
    userId: 6,
    userName: "StormBringer",
    userSlug: "storm-bringer",
    level: 78,
    rebirthLevel: 0,
    className: "Warrior",
    classIcon: "warrior",
    nationText: "Karus",
    expPercentage: 85,
    formattedLoyalty: "68,200",
    symbol: "storm",
    clanId: 4,
    clanName: "Thunder",
    clanSlug: "thunder",
    clanIcon: null,
    titleName: null,
    rank: 6,
  },
  {
    userId: 7,
    userName: "DarkPaladin",
    userSlug: "dark-paladin",
    level: 77,
    rebirthLevel: 1,
    className: "Priest",
    classIcon: "priest",
    nationText: "Karus",
    expPercentage: 20,
    formattedLoyalty: "62,100",
    symbol: "none",
    clanId: 1,
    clanName: "BlackLegion",
    clanSlug: "black-legion",
    clanIcon: null,
    titleName: null,
    rank: 7,
  },
  {
    userId: 8,
    userName: "FireLord",
    userSlug: "fire-lord",
    level: 76,
    rebirthLevel: 0,
    className: "Mage",
    classIcon: "mage",
    nationText: "Human",
    expPercentage: 55,
    formattedLoyalty: "58,900",
    symbol: "fire",
    clanId: 5,
    clanName: "Inferno",
    clanSlug: "inferno",
    clanIcon: null,
    titleName: null,
    rank: 8,
  },
]

export const mockClans = [
  {
    clanId: 1,
    clanName: "BlackLegion",
    clanSlug: "black-legion",
    nation: 1,
    nationText: "Karus",
    flag: 1,
    clanSymbol: "dragon",
    clanLevelText: "Level 5",
    points: 1250000,
    formattedPoints: "1,250,000",
    clanPointFund: 85000,
    formattedClanPointFund: "85,000",
    members: 48,
    clanIcon: null,
    rank: 1,
    animation: { grade: 5 },
  },
  {
    clanId: 2,
    clanName: "Phoenix",
    clanSlug: "phoenix",
    nation: 2,
    nationText: "Human",
    flag: 2,
    clanSymbol: "phoenix",
    clanLevelText: "Level 4",
    points: 980000,
    formattedPoints: "980,000",
    clanPointFund: 72000,
    formattedClanPointFund: "72,000",
    members: 45,
    clanIcon: null,
    rank: 2,
    animation: { grade: 4 },
  },
  {
    clanId: 3,
    clanName: "Frozen",
    clanSlug: "frozen",
    nation: 2,
    nationText: "Human",
    flag: 3,
    clanSymbol: "ice",
    clanLevelText: "Level 4",
    points: 750000,
    formattedPoints: "750,000",
    clanPointFund: 54000,
    formattedClanPointFund: "54,000",
    members: 42,
    clanIcon: null,
    rank: 3,
    animation: { grade: 4 },
  },
  {
    clanId: 4,
    clanName: "Thunder",
    clanSlug: "thunder",
    nation: 1,
    nationText: "Karus",
    flag: 4,
    clanSymbol: "storm",
    clanLevelText: "Level 3",
    points: 620000,
    formattedPoints: "620,000",
    clanPointFund: 45000,
    formattedClanPointFund: "45,000",
    members: 38,
    clanIcon: null,
    rank: 4,
    animation: { grade: 3 },
  },
  {
    clanId: 5,
    clanName: "Inferno",
    clanSlug: "inferno",
    nation: 2,
    nationText: "Human",
    flag: 5,
    clanSymbol: "fire",
    clanLevelText: "Level 3",
    points: 540000,
    formattedPoints: "540,000",
    clanPointFund: 38000,
    formattedClanPointFund: "38,000",
    members: 35,
    clanIcon: null,
    rank: 5,
    animation: { grade: 3 },
  },
  {
    clanId: 6,
    clanName: "ShadowKings",
    clanSlug: "shadow-kings",
    nation: 1,
    nationText: "Karus",
    flag: 6,
    clanSymbol: "skull",
    clanLevelText: "Level 2",
    points: 420000,
    formattedPoints: "420,000",
    clanPointFund: 28000,
    formattedClanPointFund: "28,000",
    members: 30,
    clanIcon: null,
    rank: 6,
    animation: { grade: 2 },
  },
]

export const mockKingElections = {
  karusKing: {
    userId: 1,
    userName: "DragonSlayer",
    userSlug: "dragon-slayer",
    clanId: 1,
    clanName: "BlackLegion",
    clanSlug: "black-legion",
    clanIcon: null,
    className: "Warrior",
    classIcon: "warrior",
    nationText: "Karus",
    nation: "karus" as const,
    votes: 1250,
    formattedVotes: "1,250",
    percentage: 45,
  },
  humanKing: {
    userId: 2,
    userName: "ShadowMage",
    userSlug: "shadow-mage",
    clanId: 2,
    clanName: "Phoenix",
    clanSlug: "phoenix",
    clanIcon: null,
    className: "Mage",
    classIcon: "mage",
    nationText: "Human",
    nation: "human" as const,
    votes: 1180,
    formattedVotes: "1,180",
    percentage: 42,
  },
  karusVotes: [
    {
      userId: 1,
      userName: "DragonSlayer",
      userSlug: "dragon-slayer",
      clanId: 1,
      clanName: "BlackLegion",
      clanSlug: "black-legion",
      clanIcon: null,
      className: "Warrior",
      classIcon: "warrior",
      nationText: "Karus",
      nation: "karus" as const,
      rank: 1,
      votes: 1250,
      formattedVotes: "1,250",
      percentage: 45,
      voters: [
        { userId: 10, userName: "KarusVoter1", userSlug: "karus-voter-1", clanId: 1, clanName: "BlackLegion", clanSlug: "black-legion", clanIcon: null, className: "Warrior", classIcon: "warrior", date: "2024-01-15" },
        { userId: 11, userName: "KarusVoter2", userSlug: "karus-voter-2", clanId: 1, clanName: "BlackLegion", clanSlug: "black-legion", clanIcon: null, className: "Mage", classIcon: "mage", date: "2024-01-14" },
      ],
    },
    {
      userId: 4,
      userName: "NightBlade",
      userSlug: "night-blade",
      clanId: 1,
      clanName: "BlackLegion",
      clanSlug: "black-legion",
      clanIcon: null,
      className: "Rogue",
      classIcon: "rogue",
      nationText: "Karus",
      nation: "karus" as const,
      rank: 2,
      votes: 890,
      formattedVotes: "890",
      percentage: 32,
      voters: [],
    },
    {
      userId: 6,
      userName: "StormBringer",
      userSlug: "storm-bringer",
      clanId: 4,
      clanName: "Thunder",
      clanSlug: "thunder",
      clanIcon: null,
      className: "Warrior",
      classIcon: "warrior",
      nationText: "Karus",
      nation: "karus" as const,
      rank: 3,
      votes: 640,
      formattedVotes: "640",
      percentage: 23,
      voters: [],
    },
  ],
  humanVotes: [
    {
      userId: 2,
      userName: "ShadowMage",
      userSlug: "shadow-mage",
      clanId: 2,
      clanName: "Phoenix",
      clanSlug: "phoenix",
      clanIcon: null,
      className: "Mage",
      classIcon: "mage",
      nationText: "Human",
      nation: "human" as const,
      rank: 1,
      votes: 1180,
      formattedVotes: "1,180",
      percentage: 42,
      voters: [
        { userId: 20, userName: "HumanVoter1", userSlug: "human-voter-1", clanId: 2, clanName: "Phoenix", clanSlug: "phoenix", clanIcon: null, className: "Priest", classIcon: "priest", date: "2024-01-15" },
        { userId: 21, userName: "HumanVoter2", userSlug: "human-voter-2", clanId: 2, clanName: "Phoenix", clanSlug: "phoenix", clanIcon: null, className: "Warrior", classIcon: "warrior", date: "2024-01-14" },
        { userId: 22, userName: "HumanVoter3", userSlug: "human-voter-3", clanId: 3, clanName: "Frozen", clanSlug: "frozen", clanIcon: null, className: "Mage", classIcon: "mage", date: "2024-01-13" },
      ],
    },
    {
      userId: 3,
      userName: "HolyPriest",
      userSlug: "holy-priest",
      clanId: 2,
      clanName: "Phoenix",
      clanSlug: "phoenix",
      clanIcon: null,
      className: "Priest",
      classIcon: "priest",
      nationText: "Human",
      nation: "human" as const,
      rank: 2,
      votes: 920,
      formattedVotes: "920",
      percentage: 33,
      voters: [],
    },
    {
      userId: 5,
      userName: "IceQueen",
      userSlug: "ice-queen",
      clanId: 3,
      clanName: "Frozen",
      clanSlug: "frozen",
      clanIcon: null,
      className: "Mage",
      classIcon: "mage",
      nationText: "Human",
      nation: "human" as const,
      rank: 3,
      votes: 700,
      formattedVotes: "700",
      percentage: 25,
      voters: [],
    },
  ],
}

export const nations = ["Tumu", "Karus", "Human"]
export const jobs = ["Tumu", "Warrior", "Rogue", "Mage", "Priest"]
export const sortOptions = {
  loyalty: "Ulusal Puan",
  level: "Seviye",
  kills: "Kill Sayisi",
}
export const clanSortOptions = {
  points: "Toplam NP",
  clanPoints: "Klan Puani",
  members: "Uye Sayisi",
}
