/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Head: typeof import('@inertiajs/react').Head
  const Link: typeof import('@inertiajs/react').Link
  const axios: typeof import('axios').default
  const createInertiaApp: typeof import('@inertiajs/react').createInertiaApp
  const createRoot: typeof import('react-dom/client').createRoot
  const hydrateRoot: typeof import('react-dom/client').hydrateRoot
  const resolvePageComponent: typeof import('laravel-vite-plugin/inertia-helpers').resolvePageComponent
  const route: typeof import('ziggy-js').route
  const router: typeof import('@inertiajs/react').router
  const t: typeof import('@/hooks').t
  const useCallback: typeof import('react').useCallback
  const useCdn: typeof import('@/hooks').useCdn
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useForm: typeof import('@inertiajs/react').useForm
  const useId: typeof import('react').useId
  const useLayout: typeof import('@/hooks').useLayout
  const useMemo: typeof import('react').useMemo
  const usePage: typeof import('@inertiajs/react').usePage
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useTranslation: typeof import('@/hooks').useTranslation
}
